language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

stages:
  - test
  - publish

jobs:
  include:
    - stage: test
      install:
        - go get -t -v ./...
        - travis_retry go get -u golang.org/x/lint/golint
        - make
      script:
        - make test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: publish
      language: node_js
      node_js: 10
      install:
        - npm install -g semantic-release@15.x.x
      script:
        - semantic-release
