language: go

go:
  - 1.13.x
  - 1.14.x

install:
  - go get -t -v ./...
  - make
script:
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: publish
      language: node_js
      node_js: 10
      install:
        - npm install -g semantic-release@15.x.x
      script:
        - semantic-release
